#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {

	require __DIR__ . '/vendor/autoload.php';

} else {

	require __DIR__ . '/../../autoload.php';
}

$application = new Symfony\Component\Console\Application('Laravel Workshop', '1.0.6');

$application->add(new \Bmartel\Workshop\Console\GeneratePackageCommand);
$application->add(new \Bmartel\Workshop\Console\GenerateMigrationCommand);
$application->add(new \Bmartel\Workshop\Console\GenerateModelCommand);

$application->run();